name: add_activities_to_db

on:
  schedule:
    - cron: '0 0 1 1 *' # runs every year, so sad '0 0 5 31 2 ?' is not recognized as cron

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./script/requirements.txt
          
      - name: execute py script # run main.py to add activities to db
        run: python ./script/main.py
          
     # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
